-- NegoTrip CRM · migration 001 · core tables, rules and seed (applied by TRAVELCRM-SETUP-001)

CREATE SCHEMA IF NOT EXISTS crm;
CREATE TABLE IF NOT EXISTS crm.schema_migration (filename text PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now(), note text);
CREATE TABLE IF NOT EXISTS crm.org (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code text NOT NULL UNIQUE, name text NOT NULL, base_currency text NOT NULL DEFAULT 'INR', timezone text NOT NULL DEFAULT 'Asia/Kolkata', active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS crm.branch (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES crm.org(id), code text NOT NULL, name text NOT NULL, city text, state text, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (org_id, code));
CREATE TABLE IF NOT EXISTS crm.staff (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES crm.org(id), branch_id uuid REFERENCES crm.branch(id), email text NOT NULL, full_name text NOT NULL, phone_e164 text, role text NOT NULL DEFAULT 'read_only' CHECK (role IN ('super_admin','company_admin','branch_manager','sales_manager','sales_executive','operations','accounts','marketing','supplier_manager','read_only')), hq_member_id text, languages text[] NOT NULL DEFAULT '{}'::text[], specialities text[] NOT NULL DEFAULT '{}'::text[], shift text, max_open_leads integer, active boolean NOT NULL DEFAULT true, last_seen_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS staff_org_email_uq ON crm.staff (org_id, lower(email));
CREATE TABLE IF NOT EXISTS crm.config (org_id uuid NOT NULL REFERENCES crm.org(id), key text NOT NULL, value jsonb NOT NULL, notes text, updated_at timestamptz NOT NULL DEFAULT now(), updated_by text, PRIMARY KEY (org_id, key));
CREATE TABLE IF NOT EXISTS crm.idempotency_key (org_id uuid NOT NULL REFERENCES crm.org(id), scope text NOT NULL, key text NOT NULL, first_seen_at timestamptz NOT NULL DEFAULT now(), result jsonb, expires_at timestamptz, PRIMARY KEY (org_id, scope, key))
;

CREATE TABLE IF NOT EXISTS crm.lead_source (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES crm.org(id), code text NOT NULL, name text NOT NULL, channel text NOT NULL CHECK (channel IN ('web','social','ads','messaging','email','phone','partner','offline','api')), quality_weight numeric(5,2) NOT NULL DEFAULT 1, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (org_id, code));
CREATE TABLE IF NOT EXISTS crm.tag (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES crm.org(id), name text NOT NULL, colour text, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS tag_org_name_uq ON crm.tag (org_id, lower(name));
CREATE SEQUENCE IF NOT EXISTS crm.customer_no_seq;
CREATE TABLE IF NOT EXISTS crm.customer (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES crm.org(id), customer_no text NOT NULL DEFAULT ('C-' || to_char(now(), 'YYMM') || '-' || lpad(nextval('crm.customer_no_seq')::text, 5, '0')), kind text NOT NULL DEFAULT 'individual' CHECK (kind IN ('individual','company','agent')), full_name text NOT NULL, company_name text, phone_e164 text, whatsapp_e164 text, email text, language text, city text, state text, country_code text, agent_code text, portal_user_id bigint, notes text, owner_staff_id uuid REFERENCES crm.staff(id), merged_into_customer_id uuid REFERENCES crm.customer(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, UNIQUE (org_id, customer_no));
CREATE INDEX IF NOT EXISTS customer_phone_ix ON crm.customer (phone_e164);
CREATE INDEX IF NOT EXISTS customer_whatsapp_ix ON crm.customer (whatsapp_e164);
CREATE INDEX IF NOT EXISTS customer_email_ix ON crm.customer (lower(email));
CREATE TABLE IF NOT EXISTS crm.customer_contact (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), customer_id uuid NOT NULL REFERENCES crm.customer(id), name text NOT NULL, role text, phone_e164 text, email text, is_primary boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS customer_contact_customer_ix ON crm.customer_contact (customer_id);
CREATE TABLE IF NOT EXISTS crm.customer_preference (customer_id uuid PRIMARY KEY REFERENCES crm.customer(id), hotel_category text, meal_plan text, vehicle text, destinations text[] NOT NULL DEFAULT '{}'::text[], language text, special_assistance text, channel_preference text CHECK (channel_preference IN ('whatsapp','email','sms','call')), notes text, updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS crm.traveller (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES crm.org(id), customer_id uuid NOT NULL REFERENCES crm.customer(id), full_name text NOT NULL, relation text, date_of_birth date, nationality_code text, meal_preference text, special_assistance text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE INDEX IF NOT EXISTS traveller_customer_ix ON crm.traveller (customer_id);
CREATE TABLE IF NOT EXISTS crm.customer_document (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES crm.org(id), customer_id uuid NOT NULL REFERENCES crm.customer(id), traveller_id uuid REFERENCES crm.traveller(id), doc_type text NOT NULL CHECK (doc_type IN ('passport','visa','national_id','ticket','invoice','voucher','insurance','contract','other')), doc_number_last4 text, doc_number_hash text, storage_provider text, storage_key text, file_name text, mime text, bytes bigint, issued_on date, expires_on date, retention_until date, uploaded_by_staff_id uuid REFERENCES crm.staff(id), created_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE INDEX IF NOT EXISTS customer_document_customer_ix ON crm.customer_document (customer_id);
CREATE INDEX IF NOT EXISTS customer_document_expiry_ix ON crm.customer_document (expires_on);
CREATE SEQUENCE IF NOT EXISTS crm.lead_no_seq;
CREATE TABLE IF NOT EXISTS crm.lead (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES crm.org(id), lead_no text NOT NULL DEFAULT ('L-' || to_char(now(), 'YYMM') || '-' || lpad(nextval('crm.lead_no_seq')::text, 5, '0')), branch_id uuid REFERENCES crm.branch(id), customer_id uuid REFERENCES crm.customer(id), source_id uuid NOT NULL REFERENCES crm.lead_source(id), source_ref text, campaign text, utm_source text, utm_medium text, utm_campaign text, utm_term text, utm_content text, gclid text, landing_page text, referrer text, full_name text, phone_e164 text, whatsapp_e164 text, email text, company_name text, audience text NOT NULL DEFAULT 'retail' CHECK (audience IN ('retail','b2b','corporate')), segment text, destination_text text, travel_start date, travel_end date, pax_adults integer, pax_children integer, pax_infants integer, budget_amount numeric(14,2), budget_currency text, message text, status text NOT NULL DEFAULT 'new' CHECK (status IN ('new','contacted','qualified','requirement_collected','quoted','negotiating','won','lost','dormant','duplicate')), lost_reason text, temperature text CHECK (temperature IN ('hot','warm','cold')), score integer, conversion_probability numeric(5,4), priority text CHECK (priority IN ('low','normal','high','urgent')), next_best_action text, owner_staff_id uuid REFERENCES crm.staff(id), first_response_at timestamptz, last_activity_at timestamptz, duplicate_of_lead_id uuid REFERENCES crm.lead(id), consent_marketing boolean, raw jsonb, correlation_id uuid, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, UNIQUE (org_id, lead_no));
CREATE UNIQUE INDEX IF NOT EXISTS lead_source_ref_uq ON crm.lead (org_id, source_id, source_ref) WHERE source_ref IS NOT NULL;
CREATE INDEX IF NOT EXISTS lead_status_ix ON crm.lead (org_id, status);
CREATE INDEX IF NOT EXISTS lead_owner_ix ON crm.lead (org_id, owner_staff_id);
CREATE INDEX IF NOT EXISTS lead_phone_ix ON crm.lead (phone_e164);
CREATE INDEX IF NOT EXISTS lead_whatsapp_ix ON crm.lead (whatsapp_e164);
CREATE INDEX IF NOT EXISTS lead_email_ix ON crm.lead (lower(email));
CREATE INDEX IF NOT EXISTS lead_created_ix ON crm.lead (created_at);
CREATE INDEX IF NOT EXISTS lead_customer_ix ON crm.lead (customer_id);
CREATE TABLE IF NOT EXISTS crm.lead_status_history (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), lead_id uuid NOT NULL REFERENCES crm.lead(id), from_status text, to_status text NOT NULL, changed_by_staff_id uuid REFERENCES crm.staff(id), changed_at timestamptz NOT NULL DEFAULT now(), reason text);
CREATE INDEX IF NOT EXISTS lead_status_history_lead_ix ON crm.lead_status_history (lead_id, changed_at);
CREATE TABLE IF NOT EXISTS crm.lead_assignment (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), lead_id uuid NOT NULL REFERENCES crm.lead(id), staff_id uuid NOT NULL REFERENCES crm.staff(id), assigned_by_staff_id uuid REFERENCES crm.staff(id), rule text, assigned_at timestamptz NOT NULL DEFAULT now(), released_at timestamptz);
CREATE INDEX IF NOT EXISTS lead_assignment_lead_ix ON crm.lead_assignment (lead_id, assigned_at);
CREATE INDEX IF NOT EXISTS lead_assignment_staff_ix ON crm.lead_assignment (staff_id, assigned_at);
CREATE TABLE IF NOT EXISTS crm.lead_score (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), lead_id uuid NOT NULL REFERENCES crm.lead(id), scored_at timestamptz NOT NULL DEFAULT now(), rule_score integer NOT NULL, ai_score integer, final_score integer NOT NULL, temperature text NOT NULL CHECK (temperature IN ('hot','warm','cold')), factors jsonb NOT NULL DEFAULT '{}'::jsonb, model text);
CREATE INDEX IF NOT EXISTS lead_score_lead_ix ON crm.lead_score (lead_id, scored_at);
CREATE TABLE IF NOT EXISTS crm.lead_note (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), lead_id uuid NOT NULL REFERENCES crm.lead(id), staff_id uuid REFERENCES crm.staff(id), body text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE INDEX IF NOT EXISTS lead_note_lead_ix ON crm.lead_note (lead_id, created_at);
CREATE TABLE IF NOT EXISTS crm.lead_tag (lead_id uuid NOT NULL REFERENCES crm.lead(id), tag_id uuid NOT NULL REFERENCES crm.tag(id), added_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (lead_id, tag_id));
CREATE TABLE IF NOT EXISTS crm.consent (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES crm.org(id), customer_id uuid REFERENCES crm.customer(id), lead_id uuid REFERENCES crm.lead(id), channel text NOT NULL CHECK (channel IN ('whatsapp','email','sms','call')), purpose text NOT NULL CHECK (purpose IN ('transactional','marketing')), granted boolean NOT NULL, source text, recorded_at timestamptz NOT NULL DEFAULT now(), recorded_by text, CHECK (customer_id IS NOT NULL OR lead_id IS NOT NULL));
CREATE INDEX IF NOT EXISTS consent_customer_ix ON crm.consent (customer_id, channel, purpose, recorded_at);
CREATE INDEX IF NOT EXISTS consent_lead_ix ON crm.consent (lead_id, channel, purpose, recorded_at)
;

CREATE TABLE IF NOT EXISTS crm.requirement (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES crm.org(id), lead_id uuid NOT NULL REFERENCES crm.lead(id), customer_id uuid REFERENCES crm.customer(id), current_version integer NOT NULL DEFAULT 0, status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','complete','quoted','closed')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS requirement_lead_ix ON crm.requirement (lead_id);
CREATE TABLE IF NOT EXISTS crm.requirement_version (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), requirement_id uuid NOT NULL REFERENCES crm.requirement(id), version_no integer NOT NULL, origin text, destination text, state text, travel_start date, travel_end date, flexible_dates boolean, nights integer, adults integer, children integer, infants integer, rooms integer, hotel_category text, meal_plan text, transport text, flights_required boolean, activities text, visa_required boolean, insurance_required boolean, budget_amount numeric(14,2), currency text, special_requirements text, stay_plan text, template_name text, source text NOT NULL DEFAULT 'manual' CHECK (source IN ('manual','form','ai_extracted','whatsapp','email','chatbot')), source_text text, extracted jsonb, confidence numeric(5,4), confirmed_by_staff_id uuid REFERENCES crm.staff(id), confirmed_at timestamptz, created_by_staff_id uuid REFERENCES crm.staff(id), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (requirement_id, version_no));
CREATE TABLE IF NOT EXISTS crm.quotation (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES crm.org(id), lead_id uuid NOT NULL REFERENCES crm.lead(id), customer_id uuid REFERENCES crm.customer(id), requirement_id uuid REFERENCES crm.requirement(id), builder text NOT NULL DEFAULT 'quick_quote_engine', current_version integer NOT NULL DEFAULT 0, status text NOT NULL DEFAULT 'requested' CHECK (status IN ('requested','generated','failed','sent','viewed','accepted','rejected','revision_requested','expired','converted')), accepted_at timestamptz, booking_id bigint, booking_ref text, sales_staff_id uuid REFERENCES crm.staff(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS quotation_lead_ix ON crm.quotation (lead_id);
CREATE INDEX IF NOT EXISTS quotation_status_ix ON crm.quotation (org_id, status);
CREATE TABLE IF NOT EXISTS crm.quotation_version (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), quotation_id uuid NOT NULL REFERENCES crm.quotation(id), version_no integer NOT NULL, requirement_version_id uuid REFERENCES crm.requirement_version(id), idempotency_key text, engine_input jsonb, engine_output_text text, quotation_no text, pricing_snapshot_id bigint, currency text, grand_total numeric(14,2), per_person numeric(14,2), pdf_link text, valid_until date, error text, requested_by_staff_id uuid REFERENCES crm.staff(id), requested_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz, UNIQUE (quotation_id, version_no));
CREATE UNIQUE INDEX IF NOT EXISTS quotation_version_idem_uq ON crm.quotation_version (idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS quotation_version_no_ix ON crm.quotation_version (quotation_no);
CREATE TABLE IF NOT EXISTS crm.quotation_event (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), quotation_id uuid NOT NULL REFERENCES crm.quotation(id), version_no integer, event_type text NOT NULL CHECK (event_type IN ('requested','generated','failed','sent','delivered','viewed','accepted','rejected','revision_requested','expired')), channel text, occurred_at timestamptz NOT NULL DEFAULT now(), actor_label text, detail jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE INDEX IF NOT EXISTS quotation_event_quotation_ix ON crm.quotation_event (quotation_id, occurred_at);
CREATE TABLE IF NOT EXISTS crm.message_template (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES crm.org(id), code text NOT NULL, channel text NOT NULL CHECK (channel IN ('whatsapp','email','sms')), purpose text NOT NULL CHECK (purpose IN ('transactional','marketing')), language text NOT NULL DEFAULT 'en', name text NOT NULL, subject text, body text NOT NULL, provider_template_name text, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (org_id, code, channel, language));
CREATE TABLE IF NOT EXISTS crm.message (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES crm.org(id), channel text NOT NULL CHECK (channel IN ('whatsapp','email','sms','call','internal')), direction text NOT NULL CHECK (direction IN ('in','out')), lead_id uuid REFERENCES crm.lead(id), customer_id uuid REFERENCES crm.customer(id), quotation_id uuid REFERENCES crm.quotation(id), booking_id bigint, staff_id uuid REFERENCES crm.staff(id), template_id uuid REFERENCES crm.message_template(id), to_address text, from_address text, subject text, body text, provider text, provider_message_id text, thread_id text, status text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','sent','delivered','read','failed','received')), error text, sent_at timestamptz, delivered_at timestamptz, read_at timestamptz, correlation_id uuid, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS message_provider_uq ON crm.message (provider, provider_message_id) WHERE provider_message_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS message_lead_ix ON crm.message (lead_id, created_at);
CREATE INDEX IF NOT EXISTS message_customer_ix ON crm.message (customer_id, created_at);
CREATE TABLE IF NOT EXISTS crm.task (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL REFERENCES crm.org(id), type text NOT NULL DEFAULT 'follow_up' CHECK (type IN ('call','follow_up','payment','document','supplier_confirmation','visa','booking','travel','other')), title text NOT NULL, body text, lead_id uuid REFERENCES crm.lead(id), customer_id uuid REFERENCES crm.customer(id), quotation_id uuid REFERENCES crm.quotation(id), booking_id bigint, owner_staff_id uuid REFERENCES crm.staff(id), created_by_staff_id uuid REFERENCES crm.staff(id), priority text NOT NULL DEFAULT 'normal' CHECK (priority IN ('low','normal','high','urgent')), due_at timestamptz, sla_minutes integer, status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','in_progress','done','cancelled')), escalated_at timestamptz, escalated_to_staff_id uuid REFERENCES crm.staff(id), completed_at timestamptz, completed_by_staff_id uuid REFERENCES crm.staff(id), dedupe_key text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS task_dedupe_uq ON crm.task (org_id, dedupe_key) WHERE dedupe_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS task_due_ix ON crm.task (org_id, status, due_at);
CREATE INDEX IF NOT EXISTS task_owner_ix ON crm.task (owner_staff_id, status, due_at);
CREATE INDEX IF NOT EXISTS task_lead_ix ON crm.task (lead_id)
;

CREATE TABLE IF NOT EXISTS crm.event (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid NOT NULL, occurred_at timestamptz NOT NULL DEFAULT now(), event_type text NOT NULL, is_audit boolean NOT NULL DEFAULT false, actor_staff_id uuid, actor_label text, lead_id uuid, customer_id uuid, requirement_id uuid, quotation_id uuid, booking_id bigint, task_id uuid, message_id uuid, correlation_id uuid, workflow text, execution_id text, detail jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE INDEX IF NOT EXISTS event_lead_ix ON crm.event (lead_id, occurred_at);
CREATE INDEX IF NOT EXISTS event_customer_ix ON crm.event (customer_id, occurred_at);
CREATE INDEX IF NOT EXISTS event_correlation_ix ON crm.event (correlation_id);
CREATE INDEX IF NOT EXISTS event_type_ix ON crm.event (org_id, event_type, occurred_at);
CREATE OR REPLACE RULE event_audit_no_update AS ON UPDATE TO crm.event WHERE OLD.is_audit DO INSTEAD NOTHING;
CREATE OR REPLACE RULE event_audit_no_delete AS ON DELETE TO crm.event WHERE OLD.is_audit DO INSTEAD NOTHING;
CREATE TABLE IF NOT EXISTS crm.error_log (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid, occurred_at timestamptz NOT NULL DEFAULT now(), workflow text, workflow_id text, execution_id text, node text, error_class text NOT NULL DEFAULT 'unknown' CHECK (error_class IN ('transient','authentication','rate_limit','validation','supplier','payment','database','critical','unknown')), http_status integer, message text, detail jsonb NOT NULL DEFAULT '{}'::jsonb, lead_id uuid, booking_id bigint, correlation_id uuid, retry_count integer NOT NULL DEFAULT 0, resolved_at timestamptz, resolved_by text);
CREATE INDEX IF NOT EXISTS error_log_time_ix ON crm.error_log (occurred_at);
CREATE INDEX IF NOT EXISTS error_log_open_ix ON crm.error_log (error_class, occurred_at) WHERE resolved_at IS NULL;
CREATE TABLE IF NOT EXISTS crm.error_queue (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid, created_at timestamptz NOT NULL DEFAULT now(), source_workflow text NOT NULL, event_type text, payload jsonb NOT NULL, error_log_id uuid REFERENCES crm.error_log(id), status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','retrying','resolved','discarded')), attempts integer NOT NULL DEFAULT 0, next_attempt_at timestamptz, resolved_at timestamptz, resolved_by text, resolution_note text);
CREATE INDEX IF NOT EXISTS error_queue_status_ix ON crm.error_queue (status, next_attempt_at);
CREATE TABLE IF NOT EXISTS crm.api_log (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), org_id uuid, occurred_at timestamptz NOT NULL DEFAULT now(), provider text NOT NULL, operation text NOT NULL, request_id text, correlation_id uuid, http_status integer, duration_ms integer, ok boolean NOT NULL, error text, meta jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE INDEX IF NOT EXISTS api_log_provider_ix ON crm.api_log (provider, occurred_at);
INSERT INTO crm.org (code, name) VALUES ('NEGOTRIP', 'Negotrip Private Limited') ON CONFLICT (code) DO NOTHING;
INSERT INTO crm.lead_source (org_id, code, name, channel) SELECT o.id, v.code, v.name, v.channel FROM crm.org o CROSS JOIN (VALUES ('website','Website','web'), ('landing_page','Landing page','web'), ('facebook_lead_ads','Facebook Lead Ads','social'), ('instagram_lead_ads','Instagram Lead Ads','social'), ('google_ads_form','Google Ads lead form','ads'), ('google_form','Google Form','web'), ('whatsapp','WhatsApp','messaging'), ('email','Email','email'), ('phone','Phone or manual entry','phone'), ('chatbot','Chatbot','messaging'), ('travel_agent','Travel agent','partner'), ('corporate','Corporate client','partner'), ('referral','Referral','offline'), ('walk_in','Walk-in','offline'), ('event','Event or exhibition','offline'), ('external_api','External API','api'), ('qr_campaign','QR campaign','offline')) AS v(code, name, channel) WHERE o.code = 'NEGOTRIP' ON CONFLICT (org_id, code) DO NOTHING;
INSERT INTO crm.schema_migration (filename, note) VALUES ('001_crm_core.sql', 'Phase 1 core tables, rules and seed') ON CONFLICT (filename) DO NOTHING
;
